version: "3"

services:
  ms-turbo-worker:
    platform: linux/amd64   # Specify the platform for the service
    build:
      context: ./
      dockerfile: Dockerfile.amd64   # Use the Dockerfile for amd64 architecture
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 12345

  postgres:
    image: postgres:latest  # Add the "latest" tag here
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    networks:
      - app_network
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest  # Add the "latest" tag here
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: r@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_LISTEN_PORT: 80
    networks:
      - app_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  app_network:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data: